In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid

In [3]:
#Dataset- https://www.kaggle.com/competitions/invicta/data
df=pd.read_csv("\inv_train.csv") 

In [4]:
df

Id  Label      0      1      2      3      4      5      6      7  \
0     1407      2  187.0  170.0  163.0  151.0  173.0  114.0  120.0  121.0   
1      666      1  104.0   48.0   33.0  127.0  187.0  127.0   69.0  115.0   
2      118      0  229.0  231.0  232.0  234.0  235.0  235.0  236.0  237.0   
3     1870      2  210.0  211.0  211.0  199.0  195.0  212.0  213.0  207.0   
4     1703      2   26.0   21.0   23.0   25.0   24.0   35.0   33.0   50.0   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1495   906      1  200.0  195.0  189.0  186.0  196.0  207.0  210.0  218.0   
1496   202      1   76.0  111.0  113.0  127.0  137.0  151.0  181.0  104.0   
1497  1583      2   89.0   90.0   94.0  102.0  100.0  100.0  115.0  117.0   
1498  2021      2   14.0   27.0   51.0  134.0   99.0   76.0   83.0  100.0   
1499   930      1  238.0  202.0  206.0  200.0  195.0  204.0  204.0  214.0   

      ...    774    775    776    777    778    779    780    781    782  \
0     ...  170.0  172.0  162.0  228.0  207.0  211.0  174.0  135.0  193.0   
1     ...   68.0  100.0  161.0  137.0   92.0   86.0  100.0   80.0  127.0   
2     ...  210.0  216.0  219.0  222.0  223.0  223.0  221.0  220.0  219.0   
3     ...  104.0   97.0   92.0   84.0   93.0   88.0   84.0   91.0   86.0   
4     ...   39.0   40.0   33.0   35.0   31.0   28.0   25.0   21.0   17.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1495  ...   89.0   52.0   67.0   86.0   94.0   96.0   60.0  107.0  116.0   
1496  ...  160.0  174.0  169.0  165.0  124.0  156.0   70.0   95.0  138.0   
1497  ...   56.0   64.0   61.0   55.0   57.0   60.0   68.0   57.0   60.0   
1498  ...   51.0   56.0   55.0   44.0   70.0  128.0   72.0   77.0   29.0   
1499  ...  208.0  194.0  184.0  184.0  214.0  218.0  236.0  253.0  255.0   

        783  
0     215.0  
1      73.0  
2     216.0  
3      77.0  
4      16.0  
...     ...  
1495  116.0  
1496  107.0  
1497   58.0  
1498   45.0  
1499  254.0  

[1500 rows x 786 columns]

In [150]:
df['Label'].value_counts() 

2    729
1    632
0    139
Name: Label, dtype: int64

In [151]:
df.to_numpy()

array([[1.407e+03, 2.000e+00, 1.870e+02, ..., 1.350e+02, 1.930e+02,
        2.150e+02],
       [6.660e+02, 1.000e+00, 1.040e+02, ..., 8.000e+01, 1.270e+02,
        7.300e+01],
       [1.180e+02, 0.000e+00, 2.290e+02, ..., 2.200e+02, 2.190e+02,
        2.160e+02],
       ...,
       [1.583e+03, 2.000e+00, 8.900e+01, ..., 5.700e+01, 6.000e+01,
        5.800e+01],
       [2.021e+03, 2.000e+00, 1.400e+01, ..., 7.700e+01, 2.900e+01,
        4.500e+01],
       [9.300e+02, 1.000e+00, 2.380e+02, ..., 2.530e+02, 2.550e+02,
        2.540e+02]])

In [152]:
df[1498:1500]

Id  Label      0      1      2      3      4      5      6      7  \
1498  2021      2   14.0   27.0   51.0  134.0   99.0   76.0   83.0  100.0   
1499   930      1  238.0  202.0  206.0  200.0  195.0  204.0  204.0  214.0   

      ...    774    775    776    777    778    779    780    781    782  \
1498  ...   51.0   56.0   55.0   44.0   70.0  128.0   72.0   77.0   29.0   
1499  ...  208.0  194.0  184.0  184.0  214.0  218.0  236.0  253.0  255.0   

        783  
1498   45.0  
1499  254.0  

[2 rows x 786 columns]

In [168]:
X=df.drop(['Id','Label'],axis=1)

X=X[0:1200]
X

0      1      2      3      4      5      6      7      8      9  \
0     187.0  170.0  163.0  151.0  173.0  114.0  120.0  121.0  112.0  110.0   
1     104.0   48.0   33.0  127.0  187.0  127.0   69.0  115.0  164.0  116.0   
2     229.0  231.0  232.0  234.0  235.0  235.0  236.0  237.0  237.0  237.0   
3     210.0  211.0  211.0  199.0  195.0  212.0  213.0  207.0  215.0  217.0   
4      26.0   21.0   23.0   25.0   24.0   35.0   33.0   50.0  111.0  119.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1195  163.0  170.0  176.0  182.0  182.0  180.0  179.0  182.0  181.0  183.0   
1196    4.0   39.0   53.0    5.0    0.0   75.0  136.0  143.0  117.0  119.0   
1197  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  254.0   
1198  145.0  144.0  144.0  144.0  143.0  143.0  143.0  143.0  142.0  142.0   
1199  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   

      ...    774    775    776    777    778    779    780    781    782  \
0     ...  170.0  172.0  162.0  228.0  207.0  211.0  174.0  135.0  193.0   
1     ...   68.0  100.0  161.0  137.0   92.0   86.0  100.0   80.0  127.0   
2     ...  210.0  216.0  219.0  222.0  223.0  223.0  221.0  220.0  219.0   
3     ...  104.0   97.0   92.0   84.0   93.0   88.0   84.0   91.0   86.0   
4     ...   39.0   40.0   33.0   35.0   31.0   28.0   25.0   21.0   17.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1195  ...  197.0  186.0  171.0  165.0  149.0  125.0  104.0   82.0   70.0   
1196  ...  148.0  143.0  136.0  130.0  127.0  112.0  115.0  119.0  108.0   
1197  ...  243.0  253.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   
1198  ...   96.0   63.0   51.0   61.0   80.0   56.0   74.0  106.0  103.0   
1199  ...  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0   

        783  
0     215.0  
1      73.0  
2     216.0  
3      77.0  
4      16.0  
...     ...  
1195   64.0  
1196   75.0  
1197  255.0  
1198  146.0  
1199  255.0  

[1200 rows x 784 columns]

In [169]:
Y=pd.DataFrame(zip(df.Label))
Y=Y[0:1200]
Y

0
0     2
1     1
2     0
3     2
4     2
...  ..
1195  1
1196  1
1197  1
1198  1
1199  1

[1200 rows x 1 columns]

In [172]:
from tensorflow.keras import datasets, layers, models


In [218]:
cnn = models.Sequential([
    layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu', input_shape=(28,28,1),use_bias=True),
    layers.MaxPooling2D((2,2)),
    
    layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    
    layers.Conv2D(filters=20, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    
    
    
    layers.Flatten(),
    layers.Dense(40, activation='relu'),
    layers.Dense(40, activation='relu'),
    
    layers.Dense(3, activation='softmax')
])


In [219]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [220]:
xn=X.to_numpy()
xn=xn.reshape(1200,28,28,1) #originally 1500 tha


yn=Y.to_numpy().reshape(1200,1)

his=cnn.fit(xn,yn,epochs=80)


Epoch 1/80
38/38 [==============================] - 8s 41ms/step - loss: 2.0549 - accuracy: 0.4625
Epoch 2/80
38/38 [==============================] - 2s 41ms/step - loss: 0.9161 - accuracy: 0.5642
Epoch 3/80
38/38 [==============================] - 2s 41ms/step - loss: 0.8877 - accuracy: 0.5700
Epoch 4/80
38/38 [==============================] - 2s 41ms/step - loss: 0.8769 - accuracy: 0.5833
Epoch 5/80
38/38 [==============================] - 2s 41ms/step - loss: 0.8525 - accuracy: 0.5908
Epoch 6/80
38/38 [==============================] - 2s 41ms/step - loss: 0.8543 - accuracy: 0.5800
Epoch 7/80
38/38 [==============================] - 2s 41ms/step - loss: 0.8536 - accuracy: 0.6000
Epoch 8/80
38/38 [==============================] - 2s 40ms/step - loss: 0.8505 - accuracy: 0.5958
Epoch 9/80
38/38 [==============================] - 1s 38ms/step - loss: 0.8343 - accuracy: 0.6267
Epoch 10/80
38/38 [==============================] - 1s 38ms/step - loss: 0.8120 - accuracy: 0.6300
Epoch 11/

In [216]:
# validation
Xvt=df.drop(['Id','Label'],axis=1)
xtt=Xvt.to_numpy()
xtt=xtt[1200:1500]
xtt=xtt.reshape(300,28,28,1)

Yvt=pd.DataFrame(zip(df.Label))
ytt=Yvt.to_numpy()
ytt=ytt[1200:1500]
ytt=ytt.reshape(300,1)

In [217]:
cnn.evaluate(xtt,ytt)

10/10 [==============================] - 1s 18ms/step - loss: 2.7925 - accuracy: 0.5533


[2.792515277862549, 0.5533333420753479]

In [179]:
dft=pd.read_csv("\inv_test.csv")

In [180]:
dft

Id      0      1      2      3      4      5      6      7      8  ...  \
0    1446  186.0  178.0  167.0  212.0  198.0  194.0  190.0  154.0  152.0  ...   
1    1863   51.0   51.0   54.0   54.0   61.0   62.0   64.0   65.0   67.0  ...   
2    1494  133.0  150.0  153.0  113.0  123.0  125.0  130.0  127.0  152.0  ...   
3    1281  153.0  160.0  166.0  146.0  161.0  172.0  175.0  166.0  163.0  ...   
4    1343  254.0  254.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
529  1075   47.0   28.0   12.0   10.0   20.0   32.0   16.0   22.0    7.0  ...   
530  1151   67.0   40.0   30.0   20.0   41.0   82.0   26.0   26.0   72.0  ...   
531   246  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  ...   
532  1923    4.0   39.0    9.0    6.0    8.0   39.0    7.0   11.0   24.0  ...   
533  1878  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  ...   

       774    775    776    777    778    779    780    781    782    783  
0    130.0  137.0   85.0  120.0  145.0  134.0  181.0  180.0  151.0  141.0  
1     96.0   91.0   93.0   89.0   85.0   85.0   86.0   77.0   75.0   74.0  
2    120.0   71.0  109.0  167.0  110.0  105.0  138.0  107.0  111.0  129.0  
3    115.0  174.0  158.0  156.0  163.0  167.0  127.0  146.0  176.0  152.0  
4    113.0  145.0  180.0  199.0  217.0  220.0  236.0  250.0  255.0  254.0  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
529   33.0   36.0   30.0   26.0   12.0   18.0   28.0   29.0  107.0   46.0  
530   31.0   95.0  101.0   80.0   89.0   71.0   59.0  105.0   45.0   41.0  
531  255.0  255.0  253.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  
532   10.0    4.0    4.0    4.0    3.0   25.0   14.0    8.0    0.0    0.0  
533  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  255.0  

[534 rows x 785 columns]

In [182]:
dftest=dft.drop(['Id'],axis=1)


In [184]:
xtest=dftest.to_numpy()
xtest=xtest.reshape(534,28,28,1)


In [185]:
# prediction = model.predict(test1.reshape(1,784))
prediction=cnn.predict(xtest)

17/17 [==============================] - 1s 15ms/step


In [186]:

prediction


array([[1.3057297e-02, 5.1204360e-01, 4.7489908e-01],
       [3.0384442e-02, 3.9463666e-01, 5.7497895e-01],
       [2.9380761e-02, 6.5989619e-01, 3.1072295e-01],
       ...,
       [1.8116644e-01, 7.3232615e-01, 8.6507410e-02],
       [3.3133061e-04, 7.1140786e-04, 9.9895728e-01],
       [6.3291900e-02, 6.7394167e-02, 8.6931390e-01]], dtype=float32)

In [187]:
prediction[0]

array([0.0130573 , 0.5120436 , 0.47489908], dtype=float32)

In [190]:
list_predict_label=[]

In [191]:
for i in range(0,534):

  ithpredict_label=prediction[i]
  predict_label=np.argmax(ithpredict_label)

  list_predict_label.append(predict_label)


In [192]:

dft_id={'Label':list_predict_label}
finaltemp=pd.DataFrame(dft_id)
final=pd.DataFrame(zip(dft.Id,finaltemp.Label))
final


0  1
0    1446  1
1    1863  2
2    1494  1
3    1281  1
4    1343  1
..    ... ..
529  1075  2
530  1151  2
531   246  1
532  1923  2
533  1878  2

[534 rows x 2 columns]

In [193]:

final = final.rename({0: 'Id', 1: 'Label'}, axis=1)
final

Id  Label
0    1446      1
1    1863      2
2    1494      1
3    1281      1
4    1343      1
..    ...    ...
529  1075      2
530  1151      2
531   246      1
532  1923      2
533  1878      2

[534 rows x 2 columns]

In [194]:
final['Label'].value_counts() 

2    317
1    194
0     23
Name: Label, dtype: int64

In [195]:
final.to_csv("C:\\Users\\redmi\\OneDrive\\Desktop\\INVICTA\\invicta\\prlevel1_63.33.csv")